language: java
jdk:
  - oraclejdk8
sudo: true
dist: trusty

before_install:
  - chmod +x gradlew

stages:
  - compile
  - test
  - buildDocker

jobs:
  include:
    - stage: compile
      script:
        - ./gradlew build

    - stage: test
      script:
        - ./gradlew test
    - stage: buildDocker
      script:
        - ./gradlew buildDocker
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push emufog/emufog

