###################################################################
#                  Input/Output Settings                          #
###################################################################
inputGraphFilePath: "/home/renderfehler/IdeaProjects/emufog/5er.brite"
exportFilePath: "out.py"

overWriteOutputFile: true

applicationAssignmentPolicy: "DefaultApplicationAssignment"
devicePlacement: "DefaultDevicePlacement"
edgeIdentifier: "DefaultEdgeIdentifier"
fogPlacement: "DefaultFogLayout"
###################################################################
#                         Basic Settings                          #
###################################################################
baseAddress: "10.0.0.0"
maxFogNodes: 100
costThreshold: 6

# TODO: Make this FogNode type specific.
edgeDeviceLatency: 0
edgeDeviceBandwidth: 1000

# Settings for Parallel building:
threadCount: 1
parallelFogBuilding: false

# TODO: Model Resource Settings.
# TODO: Add fields to dynamic class loading.

###################################################################
#                         DeviceNodeTypes                         #
###################################################################
deviceNodeTypes:

    - name: deviceNode1
      scalingFactor: 1
      averageDeviceCount: 1
      memoryLimit: 524288000
      cpuShare: 1

    - name: deviceNode2
      scalingFactor: 1
      averageDeviceCount: 1
      memoryLimit: 524288000
      cpuShare: 1

###################################################################
#                         FogNodeTypes                            #
###################################################################
fogNodeTypes:

  - name: fogNodeType1
    id: 1
    maximumConnections: 1
    costs: 1
    memoryLimit: 1048576000
    cpuShare: 1

  - name: fogNodeType2
    id: 2
    maximumConnections: 1
    costs: 1
    memoryLimit: 1048576000
    cpuShare: 1

###################################################################
#                         Applications                            #
###################################################################

fogApplications:
  # TODO: Main idea behind using yaml as settings file is possibility to copy "service" definitions from docker-compose files to emuFog.
  - name: serviceA
    container:
      image: ubuntu:trusty

  - name: serviceB
    container:
      image: ubuntu:trusty

  - name: serviceC
    container:
      image: ubuntu:trusty

deviceApplications:

  - name: serviceA
    container:
      image: ubuntu:trusty

  - name: serviceB
    container:
      image: ubuntu:trusty

  - name: serviceC
    container:
      image: ubuntu:trusty


