baseAddress: 10.0.0.0
overwrite-experiment-file: true
max-fog-modes: 100
costThreshold: 6
hostDeviceLatency: 0
hostDeviceBandwidth: 1000
threadCount: 1
paralleledFogBuilding: false
deviceNodeTypes:
  - DockerImage:
      Name: ubuntu
      Version: latest
    ScalingFactor: 1
    AverageDeviceCount: 1
    MemoryLimit: 524288000
    CPUShare: 1
dogNodeTypes:
  - ID: 1
    DockerImage:
      Name: ubuntu
      Version: trusty
    MaximumConnections: 1
    Costs: 1
    MemoryLimit: 1048576000
    CPUShare: 1
  - ID: 2
    DockerImage:
      Name: debian
    MaximumConnections: 5
    Costs: 2.5
    MemoryLimit: 1048576000
    CPUShare: 1.5
